name: Just for test that send test.txt to private ec2 instance through bastion host 

on:
  push:
    branches: [ "main" ]
    
env:
  BASTION_HOST_PEM_KEY: ${{ secrets.BASTION_HOST_PEM_KEY }}
  PRIVATE_EC2_PEM_KEY: ${{ secrets.PRIVATE_EC2_PEM_KEY }}
  BASTION_HOST_IP: ${{ secrets.BASTION_HOST_IP }}
  PRIVATE_EC2_IP: ${{ secrets.PRIVATE_EC2_IP }}

jobs:
  just-send:
    runs-on: ubuntu-latest
    steps:
      - name: Check where is it
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          ls
          
      - name: Send test.txt to private ec2
        run: |
          set -e
          set -x
          
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i $BASTION_PRIVATE_KEY test.txt ec2-user@${{ env.BASTION_HOST_IP }}:~/
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i $BASTION_PRIVATE_KEY -J ec2-user@${{ env.BASTION_HOST_IP }} "scp -i $PRIVATE_EC2_KEY /home/ec2-user/test.txt ec2-user@${{ env.PRIVATE_EC2_IP }}:~/"
