name: Just for test that send test.txt to private ec2 instance through bastion host 

on:
  push:
    branches: [ "main" ]

jobs:
  just-send:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.2
          
      - name: Check to print IP
        run: |
          echo ${{ steps.ip.outputs }}
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Create Bastion PEM Key File
        run: |
          echo "${{ secrets.BASTION_HOST_PEM_KEY }}" > bastion.pem
          chmod 400 bastion.pem
        
      - name: Authorize GitHub Actions IP in Bastion Host Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.BASTION_SECURITY_GROUP_ID }} \
          --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
          
      - name: Get SSH host keys
        run: |
          ssh-keyscan -H ${{ secrets.BASTION_HOST_IP }} >> known_hosts
          ssh-keyscan -H ${{ secrets.PRIVATE_EC2_IP }} >> known_hosts
        continue-on-error: true
          
      - name: Send test.txt to private ec2
        run: |
          set -e
          set -x
          
          echo "테스트 가즈아!" > test.txt
          ls
          
          bastion_host_ip="${{ secrets.BASTION_HOST_IP }}"

          scp -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -i bastion.pem \
            test.txt ec2-user@"$bastion_host_ip":~/
        continue-on-error: true
          
      - name: Revoke GitHub Actions IP in Bastion Host Security Group
        run: |
          aws ec2 revoke-security-group-ingress \
          --group-id ${{ secrets.BASTION_SECURITY_GROUP_ID }} \
          --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        continue-on-error: true
        
      - name: Clean up
        run: |
          rm test.txt
          rm bastion.pem
        continue-on-error: true
