name: Just for test that send test.txt to private ec2 instance through bastion host 

on:
  push:
    branches: [ "main" ]

jobs:
  just-send:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.2
          
      - name: Check to print IP
        run: |
          echo ${{ steps.ip.outputs }}
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
        
      - name: Authorize GitHub Actions IP in Bastion Host Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.BASTION_SECURITY_GROUP_ID }} \
          --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Authorize Bastion Host IP in Private EC2 Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.PRIVATE_EC2_SECURITY_GROUP_ID }} \
          --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
          
      - name: Send test.txt to private ec2
        run: |
          set -e
          set -x
          
          echo "테스트 가즈아!!!" > test.txt
          ls
          
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.BASTION_HOST_PRIVATE_KEY }}"
          ssh-add - <<< "${{ secrets.PRIVATE_EC2_PRIVATE_KEY }}"

          scp -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          test.txt ec2-user@${{ secrets.BASTION_HOST_IP }}:~/

          ssh -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          -J ec2-user@${{ secrets.BASTION_HOST_IP }} \
          "scp /home/ec2-user/test.txt ec2-user@${{ secrets.PRIVATE_EC2_IP }}:~/"
        continue-on-error: true
          
      - name: Revoke GitHub Actions IP in Bastion Host Security Group
        run: |
          aws ec2 revoke-security-group-ingress \
          --group-id ${{ secrets.BASTION_SECURITY_GROUP_ID }} \
          --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        continue-on-error: true
          
      - name: Revoke Bastion Host IP in Private EC2 Security Group
        run: |
          aws ec2 revoke-security-group-ingress \
          --group-id ${{ secrets.PRIVATE_EC2_SECURITY_GROUP_ID }} \
          --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        continue-on-error: true
